name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge README.md files
        run: |
          cat .github/README.md Assets/Documentation~/README.md >> README_testing.md
